worker:
    replicas: 6
    resources:
      limits:
        cpu: 1
        memory: 7.5G
      requests:
        cpu: 1
        memory: 7.5G
    env:
      - name: EXTRA_PIP_PACKAGES
        value: gcsfs joblib dask-ml scikit-learn --upgrade
 
jupyter:
    enabled: true
    env:
        - name: EXTRA_PIP_PACKAGES
          value: gcsfs joblib dask-ml scikit-learn --upgrade