worker:
    replicas: 6
    resources:
      limits:
        cpu: 1
        memory: 5G
      requests:
        cpu: 1
        memory: 3G
    env:
      - name: EXTRA_PIP_PACKAGES
        value: gcsfs pandas numpy pymongo dask joblib dask-ml python-dotenv scikit-learn --upgrade
 
jupyter:
    enabled: false
    env:
        - name: EXTRA_PIP_PACKAGES
          value: pandas numpy pymongo dask joblib dask-ml python-dotenv scikit-learn --upgrade